# Generated by cpp11: do not edit by hand

poly_primitive_type <- function(geometries) {
  .Call(`_polyclid_poly_primitive_type`, geometries)
}

poly_length <- function(geometries) {
  .Call(`_polyclid_poly_length`, geometries)
}

poly_definition_names <- function(geometries) {
  .Call(`_polyclid_poly_definition_names`, geometries)
}

poly_definition <- function(geometries, which, element) {
  .Call(`_polyclid_poly_definition`, geometries, which, element)
}

poly_set_definition <- function(geometries, which, element, value) {
  .Call(`_polyclid_poly_set_definition`, geometries, which, element, value)
}

poly_vertex <- function(geometries, which) {
  .Call(`_polyclid_poly_vertex`, geometries, which)
}

poly_set_vertex <- function(geometries, which, value) {
  .Call(`_polyclid_poly_set_vertex`, geometries, which, value)
}

poly_edges <- function(geometries, which) {
  .Call(`_polyclid_poly_edges`, geometries, which)
}

poly_cardinality <- function(geometries) {
  .Call(`_polyclid_poly_cardinality`, geometries)
}

poly_n_edges <- function(geometries) {
  .Call(`_polyclid_poly_n_edges`, geometries)
}

poly_subset <- function(geometries, index) {
  .Call(`_polyclid_poly_subset`, geometries, index)
}

poly_copy <- function(geometries) {
  .Call(`_polyclid_poly_copy`, geometries)
}

poly_assign <- function(geometries, index, value) {
  .Call(`_polyclid_poly_assign`, geometries, index, value)
}

poly_combine <- function(geometries, extra) {
  .Call(`_polyclid_poly_combine`, geometries, extra)
}

poly_unique <- function(geometries) {
  .Call(`_polyclid_poly_unique`, geometries)
}

poly_duplicated <- function(geometries) {
  .Call(`_polyclid_poly_duplicated`, geometries)
}

poly_any_duplicated <- function(geometries) {
  .Call(`_polyclid_poly_any_duplicated`, geometries)
}

poly_is_na <- function(geometries) {
  .Call(`_polyclid_poly_is_na`, geometries)
}

poly_any_na <- function(geometries) {
  .Call(`_polyclid_poly_any_na`, geometries)
}

poly_to_matrix <- function(geometries) {
  .Call(`_polyclid_poly_to_matrix`, geometries)
}

poly_format <- function(geometries) {
  .Call(`_polyclid_poly_format`, geometries)
}

poly_is_equal <- function(geometries1, geometries2) {
  .Call(`_polyclid_poly_is_equal`, geometries1, geometries2)
}

poly_transform <- function(geometries, affine) {
  .Call(`_polyclid_poly_transform`, geometries, affine)
}

poly_bbox <- function(geometries) {
  .Call(`_polyclid_poly_bbox`, geometries)
}

poly_approx_length <- function(geometries) {
  .Call(`_polyclid_poly_approx_length`, geometries)
}

poly_approx_area <- function(geometries) {
  .Call(`_polyclid_poly_approx_area`, geometries)
}

poly_reverse_orientation <- function(poly) {
  .Call(`_polyclid_poly_reverse_orientation`, poly)
}

polygon_make_valid <- function(poly) {
  .Call(`_polyclid_polygon_make_valid`, poly)
}

polygon_connect_holes <- function(poly) {
  .Call(`_polyclid_polygon_connect_holes`, poly)
}

poly_is_degenerate <- function(geometries) {
  .Call(`_polyclid_poly_is_degenerate`, geometries)
}

poly_has_point_inside <- function(geometries, points) {
  .Call(`_polyclid_poly_has_point_inside`, geometries, points)
}

poly_has_point_on <- function(geometries, points) {
  .Call(`_polyclid_poly_has_point_on`, geometries, points)
}

poly_has_point_outside <- function(geometries, points) {
  .Call(`_polyclid_poly_has_point_outside`, geometries, points)
}

poly_has_point_on_positive <- function(geometries, points) {
  .Call(`_polyclid_poly_has_point_on_positive`, geometries, points)
}

poly_has_point_on_negative <- function(geometries, points) {
  .Call(`_polyclid_poly_has_point_on_negative`, geometries, points)
}

polygon_is_valid <- function(poly) {
  .Call(`_polyclid_polygon_is_valid`, poly)
}

polygon_is_clockwise <- function(poly) {
  .Call(`_polyclid_polygon_is_clockwise`, poly)
}

polygon_is_counterclockwise <- function(poly) {
  .Call(`_polyclid_polygon_is_counterclockwise`, poly)
}

polygon_is_convex <- function(poly) {
  .Call(`_polyclid_polygon_is_convex`, poly)
}

polygon_is_simple <- function(poly) {
  .Call(`_polyclid_polygon_is_simple`, poly)
}

polygon_is_relatively_simple <- function(poly) {
  .Call(`_polyclid_polygon_is_relatively_simple`, poly)
}

polygon_is_collinear <- function(poly) {
  .Call(`_polyclid_polygon_is_collinear`, poly)
}

polyline_is_x_monotone <- function(poly) {
  .Call(`_polyclid_polyline_is_x_monotone`, poly)
}

polyline_is_y_monotone <- function(poly) {
  .Call(`_polyclid_polyline_is_y_monotone`, poly)
}

polyline_is_x_weakly_monotone <- function(poly) {
  .Call(`_polyclid_polyline_is_x_weakly_monotone`, poly)
}

polyline_is_y_weakly_monotone <- function(poly) {
  .Call(`_polyclid_polyline_is_y_weakly_monotone`, poly)
}

polyline_is_selfintersecting <- function(poly) {
  .Call(`_polyclid_polyline_is_selfintersecting`, poly)
}

create_polygonset_empty <- function() {
  .Call(`_polyclid_create_polygonset_empty`)
}

create_polygonset_polygon <- function(p) {
  .Call(`_polyclid_create_polygonset_polygon`, p)
}

create_polygonset_list <- function(p) {
  .Call(`_polyclid_create_polygonset_list`, p)
}

polygonset_n_polygons <- function(geometries) {
  .Call(`_polyclid_polygonset_n_polygons`, geometries)
}

polygonset_get_polygon <- function(geometries, which) {
  .Call(`_polyclid_polygonset_get_polygon`, geometries, which)
}

polygonset_get_all_polygon <- function(geometries) {
  .Call(`_polyclid_polygonset_get_all_polygon`, geometries)
}

polygonset_complement <- function(geometries) {
  .Call(`_polyclid_polygonset_complement`, geometries)
}

polygonset_union <- function(geometries, other) {
  .Call(`_polyclid_polygonset_union`, geometries, other)
}

polygonset_intersection <- function(geometries, other) {
  .Call(`_polyclid_polygonset_intersection`, geometries, other)
}

polygonset_difference <- function(geometries, other) {
  .Call(`_polyclid_polygonset_difference`, geometries, other)
}

polygonset_symmetric_difference <- function(geometries, other) {
  .Call(`_polyclid_polygonset_symmetric_difference`, geometries, other)
}

polygonset_cum_union <- function(geometries) {
  .Call(`_polyclid_polygonset_cum_union`, geometries)
}

polygonset_cum_intersection <- function(geometries) {
  .Call(`_polyclid_polygonset_cum_intersection`, geometries)
}

polygonset_cum_difference <- function(geometries) {
  .Call(`_polyclid_polygonset_cum_difference`, geometries)
}

polygonset_cum_symmetric_difference <- function(geometries) {
  .Call(`_polyclid_polygonset_cum_symmetric_difference`, geometries)
}

polygonset_do_intersect <- function(geometries, other) {
  .Call(`_polyclid_polygonset_do_intersect`, geometries, other)
}

polygonset_locate <- function(geometries, points) {
  .Call(`_polyclid_polygonset_locate`, geometries, points)
}

create_polygon_empty <- function() {
  .Call(`_polyclid_create_polygon_empty`)
}

create_polygon_single <- function(p) {
  .Call(`_polyclid_create_polygon_single`, p)
}

create_polygon_list <- function(ps) {
  .Call(`_polyclid_create_polygon_list`, ps)
}

create_polygon_list_list <- function(pss) {
  .Call(`_polyclid_create_polygon_list_list`, pss)
}

create_polygon_triangle <- function(triangles) {
  .Call(`_polyclid_create_polygon_triangle`, triangles)
}

polygon_sub_cardinality <- function(geometries) {
  .Call(`_polyclid_polygon_sub_cardinality`, geometries)
}

polygon_n_holes <- function(geometries) {
  .Call(`_polyclid_polygon_n_holes`, geometries)
}

polygon_is_unbounded <- function(geometries) {
  .Call(`_polyclid_polygon_is_unbounded`, geometries)
}

polygon_get_boundary <- function(geometries) {
  .Call(`_polyclid_polygon_get_boundary`, geometries)
}

polygon_set_boundary <- function(geometries, other) {
  .Call(`_polyclid_polygon_set_boundary`, geometries, other)
}

polygon_get_hole <- function(geometries, which) {
  .Call(`_polyclid_polygon_get_hole`, geometries, which)
}

polygon_remove_hole <- function(geometries, which) {
  .Call(`_polyclid_polygon_remove_hole`, geometries, which)
}

polygon_add_hole <- function(geometries, other) {
  .Call(`_polyclid_polygon_add_hole`, geometries, other)
}

polygon_set_hole <- function(geometries, which, other) {
  .Call(`_polyclid_polygon_set_hole`, geometries, which, other)
}

create_polylineset_empty <- function() {
  .Call(`_polyclid_create_polylineset_empty`)
}

create_polylineset_polyline <- function(p) {
  .Call(`_polyclid_create_polylineset_polyline`, p)
}

create_polylineset_list <- function(p) {
  .Call(`_polyclid_create_polylineset_list`, p)
}

polylineset_n_polylines <- function(geometries) {
  .Call(`_polyclid_polylineset_n_polylines`, geometries)
}

polylineset_n_polylines_simplified <- function(geometries) {
  .Call(`_polyclid_polylineset_n_polylines_simplified`, geometries)
}

polylineset_get_polylines <- function(geometries, which) {
  .Call(`_polyclid_polylineset_get_polylines`, geometries, which)
}

polylineset_get_all_polylines <- function(geometries) {
  .Call(`_polyclid_polylineset_get_all_polylines`, geometries)
}

polylineset_get_polylines_simplified <- function(geometries, which) {
  .Call(`_polyclid_polylineset_get_polylines_simplified`, geometries, which)
}

polylineset_get_all_polylines_simplified <- function(geometries) {
  .Call(`_polyclid_polylineset_get_all_polylines_simplified`, geometries)
}

polylineset_vert_degree <- function(geometries) {
  .Call(`_polyclid_polylineset_vert_degree`, geometries)
}

polylineset_vert_neighbors <- function(geometries) {
  .Call(`_polyclid_polylineset_vert_neighbors`, geometries)
}

polylineset_polyline_verts <- function(geometries) {
  .Call(`_polyclid_polylineset_polyline_verts`, geometries)
}

polylineset_n_faces <- function(geometries) {
  .Call(`_polyclid_polylineset_n_faces`, geometries)
}

polylineset_get_faces <- function(geometries) {
  .Call(`_polyclid_polylineset_get_faces`, geometries)
}

polylineset_union <- function(geometries, other) {
  .Call(`_polyclid_polylineset_union`, geometries, other)
}

polylineset_intersection <- function(geometries, other) {
  .Call(`_polyclid_polylineset_intersection`, geometries, other)
}

polylineset_difference <- function(geometries, other) {
  .Call(`_polyclid_polylineset_difference`, geometries, other)
}

polylineset_symmetric_difference <- function(geometries, other) {
  .Call(`_polyclid_polylineset_symmetric_difference`, geometries, other)
}

polylineset_cum_union <- function(geometries) {
  .Call(`_polyclid_polylineset_cum_union`, geometries)
}

polylineset_cum_intersection <- function(geometries) {
  .Call(`_polyclid_polylineset_cum_intersection`, geometries)
}

polylineset_cum_difference <- function(geometries) {
  .Call(`_polyclid_polylineset_cum_difference`, geometries)
}

polylineset_cum_symmetric_difference <- function(geometries) {
  .Call(`_polyclid_polylineset_cum_symmetric_difference`, geometries)
}

polylineset_do_intersect <- function(geometries, other) {
  .Call(`_polyclid_polylineset_do_intersect`, geometries, other)
}

polylineset_polygonset_union <- function(geometries, other) {
  .Call(`_polyclid_polylineset_polygonset_union`, geometries, other)
}

polylineset_polygonset_intersection <- function(geometries, other) {
  .Call(`_polyclid_polylineset_polygonset_intersection`, geometries, other)
}

polylineset_polygonset_difference <- function(geometries, other) {
  .Call(`_polyclid_polylineset_polygonset_difference`, geometries, other)
}

polygonset_polylineset_difference <- function(geometries, other) {
  .Call(`_polyclid_polygonset_polylineset_difference`, geometries, other)
}

polylineset_polygonset_symmetric_difference <- function(geometries, other) {
  .Call(`_polyclid_polylineset_polygonset_symmetric_difference`, geometries, other)
}

create_polyline_empty <- function() {
  .Call(`_polyclid_create_polyline_empty`)
}

create_polyline_single <- function(p) {
  .Call(`_polyclid_create_polyline_single`, p)
}

create_polyline_list <- function(ps) {
  .Call(`_polyclid_create_polyline_list`, ps)
}

create_polyline_segment <- function(segments) {
  .Call(`_polyclid_create_polyline_segment`, segments)
}
