# Generated by cpp11: do not edit by hand

poly_primitive_type <- function(geometries) {
  .Call(`_polyclid_poly_primitive_type`, geometries)
}

poly_length <- function(geometries) {
  .Call(`_polyclid_poly_length`, geometries)
}

poly_definition_names <- function(geometries) {
  .Call(`_polyclid_poly_definition_names`, geometries)
}

poly_definition <- function(geometries, which, element) {
  .Call(`_polyclid_poly_definition`, geometries, which, element)
}

poly_set_definition <- function(geometries, which, element, value) {
  .Call(`_polyclid_poly_set_definition`, geometries, which, element, value)
}

poly_vertex <- function(geometries, which) {
  .Call(`_polyclid_poly_vertex`, geometries, which)
}

poly_set_vertex <- function(geometries, which, value) {
  .Call(`_polyclid_poly_set_vertex`, geometries, which, value)
}

poly_edges <- function(geometries, which) {
  .Call(`_polyclid_poly_edges`, geometries, which)
}

poly_cardinality <- function(geometries) {
  .Call(`_polyclid_poly_cardinality`, geometries)
}

poly_n_edges <- function(geometries) {
  .Call(`_polyclid_poly_n_edges`, geometries)
}

poly_subset <- function(geometries, index) {
  .Call(`_polyclid_poly_subset`, geometries, index)
}

poly_copy <- function(geometries) {
  .Call(`_polyclid_poly_copy`, geometries)
}

poly_assign <- function(geometries, index, value) {
  .Call(`_polyclid_poly_assign`, geometries, index, value)
}

poly_combine <- function(geometries, extra) {
  .Call(`_polyclid_poly_combine`, geometries, extra)
}

poly_unique <- function(geometries) {
  .Call(`_polyclid_poly_unique`, geometries)
}

poly_duplicated <- function(geometries) {
  .Call(`_polyclid_poly_duplicated`, geometries)
}

poly_any_duplicated <- function(geometries) {
  .Call(`_polyclid_poly_any_duplicated`, geometries)
}

poly_is_na <- function(geometries) {
  .Call(`_polyclid_poly_is_na`, geometries)
}

poly_any_na <- function(geometries) {
  .Call(`_polyclid_poly_any_na`, geometries)
}

poly_to_matrix <- function(geometries) {
  .Call(`_polyclid_poly_to_matrix`, geometries)
}

poly_format <- function(geometries) {
  .Call(`_polyclid_poly_format`, geometries)
}

poly_is_equal <- function(geometries1, geometries2) {
  .Call(`_polyclid_poly_is_equal`, geometries1, geometries2)
}

poly_transform <- function(geometries, affine) {
  .Call(`_polyclid_poly_transform`, geometries, affine)
}

poly_bbox <- function(geometries) {
  .Call(`_polyclid_poly_bbox`, geometries)
}

poly_approx_length <- function(geometries) {
  .Call(`_polyclid_poly_approx_length`, geometries)
}

poly_approx_area <- function(geometries) {
  .Call(`_polyclid_poly_approx_area`, geometries)
}

poly_reverse_orientation <- function(poly) {
  .Call(`_polyclid_poly_reverse_orientation`, poly)
}

polygon_make_valid <- function(poly) {
  .Call(`_polyclid_polygon_make_valid`, poly)
}

polygon_connect_holes <- function(poly) {
  .Call(`_polyclid_polygon_connect_holes`, poly)
}

poly_is_degenerate <- function(geometries) {
  .Call(`_polyclid_poly_is_degenerate`, geometries)
}

poly_has_point_inside <- function(geometries, points) {
  .Call(`_polyclid_poly_has_point_inside`, geometries, points)
}

poly_has_point_on <- function(geometries, points) {
  .Call(`_polyclid_poly_has_point_on`, geometries, points)
}

poly_has_point_outside <- function(geometries, points) {
  .Call(`_polyclid_poly_has_point_outside`, geometries, points)
}

poly_has_point_on_positive <- function(geometries, points) {
  .Call(`_polyclid_poly_has_point_on_positive`, geometries, points)
}

poly_has_point_on_negative <- function(geometries, points) {
  .Call(`_polyclid_poly_has_point_on_negative`, geometries, points)
}

polygon_is_valid <- function(poly) {
  .Call(`_polyclid_polygon_is_valid`, poly)
}

polygon_is_clockwise <- function(poly) {
  .Call(`_polyclid_polygon_is_clockwise`, poly)
}

polygon_is_counterclockwise <- function(poly) {
  .Call(`_polyclid_polygon_is_counterclockwise`, poly)
}

polygon_is_convex <- function(poly) {
  .Call(`_polyclid_polygon_is_convex`, poly)
}

polygon_is_simple <- function(poly) {
  .Call(`_polyclid_polygon_is_simple`, poly)
}

polygon_is_relatively_simple <- function(poly) {
  .Call(`_polyclid_polygon_is_relatively_simple`, poly)
}

polygon_is_collinear <- function(poly) {
  .Call(`_polyclid_polygon_is_collinear`, poly)
}

polyline_is_x_monotone <- function(poly) {
  .Call(`_polyclid_polyline_is_x_monotone`, poly)
}

polyline_is_y_monotone <- function(poly) {
  .Call(`_polyclid_polyline_is_y_monotone`, poly)
}

polyline_is_x_weakly_monotone <- function(poly) {
  .Call(`_polyclid_polyline_is_x_weakly_monotone`, poly)
}

polyline_is_y_weakly_monotone <- function(poly) {
  .Call(`_polyclid_polyline_is_y_weakly_monotone`, poly)
}

polyline_is_selfintersecting <- function(poly) {
  .Call(`_polyclid_polyline_is_selfintersecting`, poly)
}

create_polygon_empty <- function() {
  .Call(`_polyclid_create_polygon_empty`)
}

create_polygon_single <- function(p) {
  .Call(`_polyclid_create_polygon_single`, p)
}

create_polygon_list <- function(ps) {
  .Call(`_polyclid_create_polygon_list`, ps)
}

create_polygon_list_list <- function(pss) {
  .Call(`_polyclid_create_polygon_list_list`, pss)
}

create_polygon_triangle <- function(triangles) {
  .Call(`_polyclid_create_polygon_triangle`, triangles)
}

polygon_sub_cardinality <- function(geometries) {
  .Call(`_polyclid_polygon_sub_cardinality`, geometries)
}

polygon_n_holes <- function(geometries) {
  .Call(`_polyclid_polygon_n_holes`, geometries)
}

polygon_get_boundary <- function(geometries) {
  .Call(`_polyclid_polygon_get_boundary`, geometries)
}

polygon_set_boundary <- function(geometries, other) {
  .Call(`_polyclid_polygon_set_boundary`, geometries, other)
}

polygon_get_hole <- function(geometries, which) {
  .Call(`_polyclid_polygon_get_hole`, geometries, which)
}

polygon_remove_hole <- function(geometries, which) {
  .Call(`_polyclid_polygon_remove_hole`, geometries, which)
}

polygon_add_hole <- function(geometries, other) {
  .Call(`_polyclid_polygon_add_hole`, geometries, other)
}

polygon_set_hole <- function(geometries, which, other) {
  .Call(`_polyclid_polygon_set_hole`, geometries, which, other)
}

create_polyline_empty <- function() {
  .Call(`_polyclid_create_polyline_empty`)
}

create_polyline_single <- function(p) {
  .Call(`_polyclid_create_polyline_single`, p)
}

create_polyline_list <- function(ps) {
  .Call(`_polyclid_create_polyline_list`, ps)
}

create_polyline_segment <- function(segments) {
  .Call(`_polyclid_create_polyline_segment`, segments)
}
